# Quick Start:
#
# pip install pre-commit
# pre-commit install && pre-commit install -t pre-push
# pre-commit run --all-files
#
# To Skip Checks:
#
# git commit --no-verify
fail_fast: false

default_language_version:
  python: python3.12

repos:
  # pre commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--django"]

  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.11"
    hooks:
      - id: ruff
        args: [--fix]

  # Conventional pre-commit
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, ci, chore, test, infra, refactor]

  # Prettier
  - repo: local
    hooks:
      - id: prettier
        name: Run prettier
        entry: npx prettier --write
        language: system
        files: \.(js|jsx|ts|tsx|json|css|scss|md|yaml|yml)$
        pass_filenames: true

  # Eslint
  - repo: local
    hooks:
      - id: eslint-frontend
        name: ESLint frontend
        entry: npx eslint
        language: system
        pass_filenames: true
        files: ^frontend/
      - id: eslint-guest-portal
        name: ESLint guest portal frontend
        entry: npx eslint
        language: system
        pass_filenames: true
        files: ^guest-portal-frontend/

default_install_hook_types:
  - pre-commit
  - commit-msg
